host: ''
password: ''
port: 3306
timeout: 5000
server: 'nprison'
cooldowns: # tid er i sekunder!
  'tpa': # permission: bungeesuite.cooldown.x
    'notdonator': 15
    'donator1': 10
    'donator2': 5